### ISSUE TITLE
Release bug: Viewing Downloads From Snackbar Crash

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#1015]
**Describe the bug**
App crashes when you download a file and then try to open it from the snackbar. Happens on **release but not debug!!**

**To Reproduce**
1. Go to a website with an image.
2. Long press and download the image. 
3. See the snack bar notification that the download completed.
4. Tap "View"
5. See crash

**Expected behavior**
We should be able to open the download from the snackbar without crashing the app.

**Screenshots**

https://user-images.githubusercontent.com/20916043/193351260-28ae238e-253a-4123-aa33-e0dade1663b2.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung
 - Android version: Android 12

**Additional context**
Another perhaps related release bug is: #1014

**Comment by Kokobe** [comment]
```
E  FATAL EXCEPTION: main
                                                                                                    Process: com.neeva.app, PID: 22559
                                                                                                    android.os.FileUriExposedException: file:///storage/emulated/0/Download/dog-puppy-on-garden-royalty-free-image-1586966191.jpg exposed beyond app through Intent.getData()
                                                                                                    	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2209)
                                                                                                    	at android.net.Uri.checkFileUriExposed(Uri.java:2402)
                                                                                                    	at android.content.Intent.prepareToLeaveProcess(Intent.java:12108)
                                                                                                    	at android.content.Intent.prepareToLeaveProcess(Intent.java:12057)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1742)
                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1135)
                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1106)
                                                                                                    	at android.content.ContextWrapper.startActivity(ContextWrapper.java:420)
                                                                                                    	at h9.a.a(Unknown Source:7)
```
