### ISSUE TITLE
Weblayer Unsupported Version Crash

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#1263]
Not sure why but when I went through FirstRun on a fresh Pixel2Avd emulator (the same one as CircleCI), I got this crash stack:

```
FATAL EXCEPTION: main
                                                                                                    Process: com.neeva.app.debug, PID: 15402
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.neeva.app.debug/com.neeva.app.NeevaActivity}: java.lang.RuntimeException: Failed to initialize WebLayer
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: java.lang.RuntimeException: Failed to initialize WebLayer
                                                                                                    	at com.neeva.app.browsing.WebLayerModel.<init>(WebLayerModel.kt:178)
                                                                                                    	at com.neeva.app.browsing.WebLayerModel.<init>(WebLayerModel.kt:116)
                                                                                                    	at com.neeva.app.DaggerNeevaBrowser_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerNeevaBrowser_HiltComponents_SingletonC.java:614)
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:100)
                                                                                                    	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:97)
                                                                                                    	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:119)
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:83)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
                                                                                                    	at com.neeva.app.NeevaActivity.getWebLayerModel$app_debug(NeevaActivity.kt:136)
                                                                                                    	at com.neeva.app.NeevaActivity$activityViewModel$2.invoke(NeevaActivity.kt:143)
                                                                                                    	at com.neeva.app.NeevaActivity$activityViewModel$2.invoke(NeevaActivity.kt:139)
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:47)
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
                                                                                                    	at com.neeva.app.NeevaActivity.getActivityViewModel$app_debug(NeevaActivity.kt:139)
                                                                                                    	at com.neeva.app.NeevaActivity.onCreate(NeevaActivity.kt:170)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7136)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7127)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
                                                                                                    Caused by: org.chromium.weblayer.UnsupportedVersionException: Unsupported WebLayer version, client version 106.0.5249.79 is not supported by implementation version <unavailable>
                                                                                                    	at org.chromium.weblayer.WebLayer.checkAvailable(WebLayer.java:105)
                                                                                                    	at org.chromium.weblayer.WebLayer.loadAsync(WebLayer.java:124)
                                                                                                    	at com.neeva.app.browsing.WebLayerFactory.load(WebLayerFactory.kt:13)
                                                                                                    	at com.neeva.app.browsing.WebLayerModel.<init>(WebLayerModel.kt:176)
                                                                                                    	at com.neeva.app.browsing.WebLayerModel.<init>(WebLayerModel.kt:116) 
                                                                                                    	at com.neeva.app.DaggerNeevaBrowser_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerNeevaBrowser_HiltComponents_SingletonC.java:614) 
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:100) 
                                                                                                    	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:97) 
                                                                                                    	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:119) 
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:83) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187) 
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153) 
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53) 
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35) 
                                                                                                    	at com.neeva.app.NeevaActivity.getWebLayerModel$app_debug(NeevaActivity.kt:136) 
                                                                                                    	at com.neeva.app.NeevaActivity$activityViewModel$2.invoke(NeevaActivity.kt:143) 
                                                                                                    	at com.neeva.app.NeevaActivity$activityViewModel$2.invoke(NeevaActivity.kt:139) 
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:47) 
                                                                                                    	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35) 
                                                                                                    	at com.neeva.app.NeevaActivity.getActivityViewModel$app_debug(NeevaActivity.kt:139) 
                                                                                                    	at com.neeva.app.NeevaActivity.onCreate(NeevaActivity.kt:170) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7136) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7127) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**To Reproduce**

https://user-images.githubusercontent.com/20916043/219229161-e6f7ebc6-e411-41f7-ae88-23b24e018a59.mov

**Expected behavior**
Shouldn't crash because of an unsupported weblayer version...

**Comment by Kokobe** [comment]
Fixed it by:
```
# open Pixel2Avd emulator
./bootstrap.sh
./scripts/install-weblayer-support-apk.sh
```
